# FIXME(starter): adjust to you security requirements
{
  config,
  ...
}:
{
  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;

    # Global settings for all hosts (literal ssh_config directives)
    settings."*" = {
      #ForwardAgent = true;
      ControlMaster = "auto";
      ControlPath = "${config.home.homeDirectory}/.ssh/sockets/S.%r@%h:%p";
      ControlPersist = "20m";
      # Avoids infinite hang if control socket connection interrupted. ex: vpn goes down/up
      ServerAliveCountMax = 3;
      ServerAliveInterval = 5; # 3 * 5s
      HashKnownHosts = true;
      AddKeysToAgent = "yes";
    };

    # Include external host configs generated by ssh-clients module
    includes = [ "config.d/hosts" ];
  };

  home.file = {
    ".ssh/config.d/.keep".text = "# Managed by Home Manager";
    ".ssh/sockets/.keep".text = "# Managed by Home Manager";
  };
}
