{
  config,
  lib,
  inputs,
  ...
}:
let
  cfg = config.networkStorage;

  # Read network storage info from nix-secrets
  networkStorageInfo = inputs.nix-secrets.networkStorageInfo or { };
  hostConfig = networkStorageInfo.${cfg.hostname} or { };
  clientConfig = hostConfig.client or { };
  sambaClientConfig = clientConfig.samba or null;

  sambaClientEnabled = cfg.client.samba.enable && sambaClientConfig != null;

  # Flatten all mounts from all servers
  allMounts =
    if sambaClientEnabled then
      lib.flatten (
        lib.mapAttrsToList (
          serverName: serverConfig:
          map (
            mount:
            mount
            // {
              serverName = serverName;
              # Use sops secret for this server (now points to password file)
              credentials = config.sops.secrets."samba-${serverName}".path;
            }
          ) (serverConfig.mounts or [ ])
        ) (sambaClientConfig.servers or { })
      )
    else
      [ ];

in
{
  options.networkStorage = {
    hostname = lib.mkOption {
      type = lib.types.str;
      default = config.networking.hostName;
      description = "Hostname to lookup in networkStorageInfo";
    };

    client.samba = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Enable Samba client mounts from nix-secrets using autofs";
      };
    };
  };

  config = lib.mkIf sambaClientEnabled {
    # We need the credentials available for the activation script
    # They are already configured in hosts/common/optional/network-storage-darwin.nix

    system.activationScripts.postActivation.text = ''
      echo "Configuring autofs for SMB mounts..."

      AUTO_MAP="/etc/auto_nixos_smb"
      AUTO_MASTER="/etc/auto_master"
      USERNAME="${config.hostSpec.username}"

      # 1. Generate the autofs map file
      cat > "$AUTO_MAP.tmp" <<EOF
      # Generated by NixOS configuration - DO NOT EDIT
      # This file contains sensitive credentials and should have 600 permissions
      EOF

      ${lib.concatMapStrings (mount: ''
        CREDENTIALS_FILE="${mount.credentials}"
        SHARE="${mount.share}"
        MOUNT_POINT="${mount.mountPoint}"

        # Ensure mount point exists explicitly to avoid "mountpoint unavailable" errors
        if [ ! -d "$MOUNT_POINT" ]; then
           echo "Creating mount point: $MOUNT_POINT"
           mkdir -p "$MOUNT_POINT"
        fi

        if [ -f "$CREDENTIALS_FILE" ]; then
           # Read password (sops file contains just the password)
           # tr -d '\n' ensures no trailing newline from cat
           PASSWORD=$(tr -d '\n' < "$CREDENTIALS_FILE")

           # URL Encode using Ruby (Standard on macOS)
           # This is cleaner than Python and handles special chars correctly
           if command -v ruby >/dev/null 2>&1; then
             USER_ENC=$(ruby -r cgi -e 'print CGI.escape(ARGV[0])' "$USERNAME")
             PASS_ENC=$(ruby -r cgi -e 'print CGI.escape(ARGV[0])' "$PASSWORD")

             CRED_DATA="$USER_ENC:$PASS_ENC"

             # Extract server path from share (remove leading //)
             SERVER_PATH=''${SHARE#//}

             # Write direct map entry
             # Format: /path/to/mount -fstype=smbfs,soft,noowners,nosuid ://user:pass@server/share
             echo "$MOUNT_POINT -fstype=smbfs,soft,noowners,nosuid ://$CRED_DATA@$SERVER_PATH" >> "$AUTO_MAP.tmp"
           else
             echo "Warning: Ruby not found, skipping autofs config for $SHARE"
           fi
        else
           echo "Warning: Credentials file not found for $SHARE"
        fi
      '') allMounts}

      # 2. Secure the map file
      chmod 600 "$AUTO_MAP.tmp"
      chown root:wheel "$AUTO_MAP.tmp"
      mv "$AUTO_MAP.tmp" "$AUTO_MAP"

      # 3. Update auto_master if needed
      if ! grep -q "^/-[[:space:]]*$AUTO_MAP" "$AUTO_MASTER"; then
        echo "Adding $AUTO_MAP to $AUTO_MASTER"
        cp "$AUTO_MASTER" "$AUTO_MASTER.bak"
        echo "/-              $AUTO_MAP" >> "$AUTO_MASTER"
      fi

      # 4. Reload automountd
      echo "Reloading automount..."
      automount -vc
    '';
  };
}
